### ISSUE TITLE
Rake tasks can't be found

### ISSUE THREAD

**Issue by ajh** [forgottentea/pg_assets#3]
```
$ be rake pg:assets:dump
rake aborted!
LoadError: cannot load such file -- ../../tasks/pg_assets.rake
/Users/ajh/.rvm/gems/ruby-2.2.2@scheduler/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/ajh/.rvm/gems/ruby-2.2.2@scheduler/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/Users/ajh/.rvm/gems/ruby-2.2.2@scheduler/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/ajh/.rvm/gems/ruby-2.2.2@scheduler/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/ajh/devel/pg_assets/lib/pg_assets/railtie.rb:15:in `block in <class:Railtie>'
```

I fixed this and the other 2 bugs in this commit: https://github.com/ajh/pg_assets/commit/081bc2183d85b010a43c21703c4368ff4cb50a90

**Comment by forgottentea** [comment]
pr pls?
